// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// If `firebase_core` package is not added to the project, provide a
// minimal local definition of `FirebaseOptions` so this file still
// compiles during development. When `firebase_core` is available,
// remove this local definition.
class FirebaseOptions {
  final String? apiKey;
  final String? appId;
  final String? messagingSenderId;
  final String? projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? measurementId;
  final String? iosBundleId;

  const FirebaseOptions({
    this.apiKey,
    this.appId,
    this.messagingSenderId,
    this.projectId,
    this.authDomain,
    this.storageBucket,
    this.measurementId,
    this.iosBundleId,
  });
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGIXAPFp00XTjWoDNov4mm2f9pUrS2w-g',
    appId: '1:271218192884:web:06c5806f3fdb6b72bdc9a1',
    messagingSenderId: '271218192884',
    projectId: 'tugas-tndividu-pab-ii',
    authDomain: 'tugas-tndividu-pab-ii.firebaseapp.com',
    storageBucket: 'tugas-tndividu-pab-ii.firebasestorage.app',
    measurementId: 'G-VDPTZPNY9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0-wFDm8Z4RUrW7DdZXPJeuMAyoLBToY',
    appId: '1:271218192884:android:5c0e9f11134f55c9bdc9a1',
    messagingSenderId: '271218192884',
    projectId: 'tugas-tndividu-pab-ii',
    storageBucket: 'tugas-tndividu-pab-ii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPivR2Zcba9Q6ozAgfnDyhNC8QvmoQMcQ',
    appId: '1:271218192884:ios:adf36acde9119036bdc9a1',
    messagingSenderId: '271218192884',
    projectId: 'tugas-tndividu-pab-ii',
    storageBucket: 'tugas-tndividu-pab-ii.firebasestorage.app',
    iosBundleId: 'com.example.tugasIndividuPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPivR2Zcba9Q6ozAgfnDyhNC8QvmoQMcQ',
    appId: '1:271218192884:ios:adf36acde9119036bdc9a1',
    messagingSenderId: '271218192884',
    projectId: 'tugas-tndividu-pab-ii',
    storageBucket: 'tugas-tndividu-pab-ii.firebasestorage.app',
    iosBundleId: 'com.example.tugasIndividuPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGIXAPFp00XTjWoDNov4mm2f9pUrS2w-g',
    appId: '1:271218192884:web:cac281c1bf1f5f14bdc9a1',
    messagingSenderId: '271218192884',
    projectId: 'tugas-tndividu-pab-ii',
    authDomain: 'tugas-tndividu-pab-ii.firebaseapp.com',
    storageBucket: 'tugas-tndividu-pab-ii.firebasestorage.app',
    measurementId: 'G-TGQR4HVCBX',
  );
}
